### ISSUE TITLE
0.66.3 Not working

### ISSUE THREAD

**Issue by showtan001** [codler/react-native-keyboard-aware-scroll-view#16]
RN 0.66.3 Android Not working

**Comment by showtan001** [comment]
![untitled](https://user-images.githubusercontent.com/32892347/147307701-3dda91c4-bd3d-43af-a025-ce83a642f024.gif)
Can't scroll at all

**Comment by codler** [comment]
Can you share code on how you use it?

**Comment by tburnt** [comment]
It crashes when I try to use a textbox

TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({
            x: x,
            y: y,
            animated: animated
          })', 'responder.scrollResponderScrollTo' is undefined)

**Comment by ahardy42** [comment]
same. crashes after upgrade to rn 0.65.3

error is line 244:30 in `KeyboardAwareHOC`

`responder.scrollResponderScrollTo is not a function`

**Comment by Mihai-github** [comment]
+1 same issue after upgrading to react-native ^0.67.5

**Comment by Srijans-nd** [comment]
any updates on the above issue, if you came across a solution - @Mihai-github @ahardy42 @showtan001  ?

**Comment by ahardy42** [comment]
I ended up upgrading the package (was using 1.0.1 and now I'm on 2.0.1) and it's working for me now.

**Comment by Srijans-nd** [comment]
thanks for the reply @ahardy42 . Which RN version are you using with 2.0.1 ?

**Comment by ahardy42** [comment]
@Srijans-nd I have an app in production using 0.65.3 and I'm in the process of upgrading to 0.68.7 and it works in both

**Comment by Srijans-nd** [comment]
Thank you so much @ahardy42 !
It's working perfectly in RN 0.67.5 app.
